# Définie les différents services du docker compose
services:
  mariadb:
    # Définie le nom du docker qui sera créer
    container_name: mariadb
    # indique l'image de nginx a utiliser
    image: mariadb
    networks:
      - inception
    # indique le répertoire et le nom du docker a build puis transmet les args de construction du docker mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        SQL_DATABASE: $SQL_DATABASE
        SQL_USER: $SQL_USER
        SQL_PWD: $SQL_PWD
        SQL_ROOT_PWD: $SQL_ROOT_PWD
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    # Créer une communication entre le docker mariadb et les container du meme reseau inception
    expose:
      - "3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
      args:
        WP_PATH: $WP_PATH
        WP_URL: $WP_URL
    env_file: .env
    # Créer un volume
    volumes:
      - wordpress:/var/www/wordpress
    # redémarre le docker en cas d'échec
    restart: on-failure
    # Créer une communication entre le docker ngin et la vm, sur le port 443
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    container_name: wordpress
    image: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]

# créer des volumes ou sera stocker les données pour avoir une persistance des données quand on stop les dockers
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $WP_VOLUME_PATH
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $MARIADB_VOLUME_PATH

# permet de connecter les différents services entre eux dans le réseau inception
networks:
  inception:
    driver: bridge
