FROM debian:11

ARG SQL_DATABASE=a
ARG SQL_USER=a
ARG SQL_PWD=a
ARG SQL_ROOT_PWD=a

RUN apt update -y
RUN apt upgrade -y
RUN apt-get install mariadb-server -y

# Envoi le ficher de configuration mariadb.conf au répertoire de configuration de MariaDB.
COPY conf/50-server.cnf	/etc/mysql/mariadb.conf.d/50-server.cnf

# Démarre le service MariaDB, puis exécute une série de commandes SQL pour créer une base de données
# et un utilisateur, donne tous les droits à l'utilisateur puis FLUSH pour actualiser la table des privilèges
RUN service mariadb start && \
    mysql -u root -e "CREATE DATABASE IF NOT EXISTS ${SQL_DATABASE}; \
    CREATE USER IF NOT EXISTS ${SQL_USER}@'localhost' IDENTIFIED BY '${SQL_PWD}'; \
    GRANT ALL PRIVILEGES ON ${SQL_DATABASE}.* TO ${SQL_USER}@'%' IDENTIFIED BY '${SQL_PWD}'; \
    ALTER USER 'root'@'localhost' IDENTIFIED BY '${SQL_ROOT_PWD}'; \
    FLUSH PRIVILEGES;" && \
    mysqladmin -u root -p$SQL_ROOT_PWD shutdown

# Lance mysql de maniere plus securisée
CMD ["mysqld_safe"]

# Permet aux autres conteneurs ou à des applications externes de se connecter à MariaDB via ce port.
EXPOSE 3306