# Nginx est un serveur web utilisé pour héberger des sites web
FROM debian:11

RUN apt update
RUN apt install nginx -y
RUN apt install vim -y
RUN apt install curl -y
# SSL est un protocole de communications sur Internet
# Chiffre les données échangées entre un navigateur web et un serveur web
RUN mkdir -p /etc/nginx/ssl
RUN apt install openssl -y
# Permet de configurer des certificats SSL/TLS.
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=Rhone/L=Lyon/0=42/OU=42/CN=mcourbon.42.fr/UID=mcourbon"
RUN mkdir -p /var/run/nginx

# Transfère le fichier nginx.conf de l'hôte vers le conteneur Nginx.
COPY conf/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx"]

# Permet aux autres conteneurs ou à des applications externes de se connecter à Nginx via ce port.
EXPOSE 443
